Add client lint check in pre-push hook

diff --git a/server/scripts/pre-push b/server/scripts/pre-push
--- a/server/scripts/pre-push
+++ b/server/scripts/pre-push
@@ -1,29 +1,10 @@
 #!/bin/sh
 
-# An example hook script to verify what is about to be pushed.  Called by "git
-# push" after it has checked the remote status, but before anything has been
-# pushed.  If this script exits with a non-zero status nothing will be pushed.
-#
-# This hook is called with the following parameters:
-#
-# $1 -- Name of the remote to which the push is being done
-# $2 -- URL to which the push is being done
-#
-# If pushing without using a named remote those arguments will be equal.
-#
-# Information about the commits which are being pushed is supplied as lines to
-# the standard input in the form:
-#
-#   <local ref> <local oid> <remote ref> <remote oid>
-#
-# This sample shows how to prevent push of commits where the log message starts
-# with "WIP" (work in progress).
-
-remote="$1"
-url="$2"
+# Adapted from: https://github.com/git/git/blob/master/templates/hooks--pre-push.sample
 
 zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')
 
+# Refer to https://git-scm.com/docs/githooks#:~:text=pre-push for argument usage
 while read local_ref local_oid remote_ref remote_oid
 do
 	if test "$local_oid" = "$zero"
@@ -42,6 +23,13 @@ do
 
 		# Check for WIP commit
 		cd server; yarn lint
+		if [ $? -ne 0 ]
+		then
+			echo >&2 "lint failed, not pushing"
+			exit 1
+		fi
+		echo "no lint errors found"
+		cd client; yarn lint
 		if [ $? -ne 0 ]
 		then
 			echo >&2 "lint failed, not pushing"
